/*
 * backup_app.h
 *
 *  Created on: Oct 30, 2024
 *      Author: william.favaro
 */

#ifndef BACKUP_H_
#define BACKUP_H_

//#include "app.h"
#include "stdbool.h"

#if 1
typedef enum
{
    APP_BUF_BACKLIGHT = 0,
    APP_BUF_LANGUAGE,
    APP_BUF_LED_INTENSITY,

    // Factory settings
    APP_BUF_BLOWER_ANALOG_CONTROL_ENABLED,
    APP_BUF_BLOWER_BYPASS_ENABLED,
    APP_BUF_FILTER_COMPRESS_AIR_ENABLED,
    APP_BUF_LINE_CLEANING_ENABLED,
    APP_BUF_PROPORTIONAL_ENABLED,
    APP_BUF_BLOWER_INTERNAL_VENTILATOR_ENABLED,
    APP_BUF_NO_AIR_PRESSURE_ENABLED,
    APP_BUF_FILTER_DUST_CONTAINER_ENABLED,
    APP_BUF_FILTER_CLOGGING_ENABLED,
    APP_BUF_RGB_LED_CONTROL_ENABLED,

    // Blower
    APP_BUF_BLOWER_SPEEDUP_TIME,
    APP_BUF_BLOWER_BYPASS_ON_DELAY_TIME,
    APP_BUF_BLOWER_VACUUM_CHARGE_TIME,
    APP_BUF_BLOWER_INTERNAL_VENTILATOR_TIME,
    APP_BUF_BLOWER_UPTIME_QUARTER_HOUR,
    APP_BUF_BLOWER_WARNING_UPTIME_HOUR,
    APP_BUF_BLOWER_ALARM_UPTIME_HOUR,
    APP_BUF_BLOWER_ANALOG_OUTPUT_ACTUAL_MV,
    APP_BUF_BLOWER_ANALOG_OUTPUT_OFF_MV,
    APP_BUF_BLOWER_ANALOG_OUTPUT_START_RAMP_MV,
    APP_BUF_BLOWER_ANALOG_OUTPUT_END_RAMP_MV,

    // Receiver
    APP_BUF_RECEIVER_1_ENABLED_BY_USER,
    APP_BUF_RECEIVER_1_GRANULAR_LEVEL_ENABLED,
    APP_BUF_RECEIVER_1_LOADING_TIMER,
    APP_BUF_RECEIVER_1_DISCHARGING_TIMER,
    APP_BUF_RECEIVER_1_WAITING_TIMER,
    APP_BUF_RECEIVER_1_ATTEMPT,
    APP_BUF_RECEIVER_1_ATTEMPT_BEFORE_AUTODISABLE,
    APP_BUF_RECEIVER_1_LINE_CLEANING_ENABLED,
    APP_BUF_RECEIVER_1_LINE_CLEANING_TIMER,
    APP_BUF_RECEIVER_1_PROPORTIONAL_ENABLED,
    APP_BUF_RECEIVER_1_PROPORTIONAL_PERCENTAGE,

    // Filter
    APP_BUF_FILTER_NUMBER_OF_CLEANING_PULSE,
    APP_BUF_FILTER_PULSE_ON_TIMER,
    APP_BUF_FILTER_PULSE_OFF_TIMER,
    APP_BUF_FILTER_PERIODIC_CLEANING_TIMER,
    APP_BUF_FILTER_UPTIME_QUARTER_HOUR

} app_buf_t;

void app_backup_init();
void app_backup_task();
#endif

#endif /* BACKUP_H_ */
